version: '3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: giviche/kittygram_backend:latest
    volumes:
      - static:/var/www/kittygram/static/
      - media:/var/www/kittygram/media/
    env_file:
      - .env

  frontend:
    image: giviche/kittygram_frontend:latest
    volumes:
      - static:/var/www/kittygram/static/

  gateway:
    image: giviche/kittygram_gateway:latest
    volumes:
      - static:/var/www/kittygram/static/
      - media:/var/www/kittygram/media/
    ports:
      - "80:80"
